export const payerList = [
    { name: '32 BJ', id: '32_BJ' },
    { name: '3M Dental Services', id: '3M' },
    { name: 'AARP Dental Insurance Plan', id: 'AARP' },
    {
        name: 'Administrative Services Only (ASO)',
        id: 'ADMINISTRATIVE_SERVICES_ONLY',
    },
    { name: 'Advantica', id: 'ADVANTICA' },
    { name: 'Aetna Dental Plans', id: 'AETNA_DENTAL_PLANS' },
    { name: 'Alan Sturm &amp; Associates', id: 'ALAN_STURM' },
    { name: 'Allegiance Benefit Plan Management, Inc.', id: 'ALLEGIANCE' },
    { name: 'Altus Dental', id: 'ALTUS' },
    { name: 'Ameritas Life Insurance Corp.', id: 'AMERITAS' },
    {
        name: 'Ameritas Life Insurance Corp. of New York',
        id: 'AMERITAS_NEW_YORK',
    },
    {
        name: 'Anthem - Blue Cross Blue Shield of Colorado',
        id: 'ANTHEM_BCBS_COLORADO',
    },
    {
        name: 'Anthem - Blue Cross Blue Shield of Connecticut',
        id: 'ANTHEM_BCBS_CONNECTICUT',
    },
    {
        name: 'Anthem - Blue Cross Blue Shield of Georgia',
        id: 'ANTHEM_BCBS_GEORGIA',
    },
    {
        name: 'Anthem - Blue Cross Blue Shield of Indiana',
        id: 'ANTHEM_BCBS_INDIANA',
    },
    {
        name: 'Anthem - Blue Cross Blue Shield of Kentucky',
        id: 'ANTHEM_BCBS_KENTUCKY',
    },
    {
        name: 'Anthem - Blue Cross Blue Shield of Maine',
        id: 'ANTHEM_BCBS_MAINE',
    },
    {
        name: 'Anthem - Blue Cross Blue Shield of Missouri',
        id: 'ANTHEM_BCBS_MISSOURI',
    },
    {
        name: 'Anthem - Blue Cross Blue Shield of Nevada',
        id: 'ANTHEM_BCBS_NEVADA',
    },
    {
        name: 'Anthem - Blue Cross Blue Shield of New Hampshire',
        id: 'ANTHEM_BCBS_NEW_HAMPSHIRE',
    },
    { name: 'Anthem - Blue Cross Blue Shield of Ohio', id: 'ANTHEM_BCBS_OHIO' },
    {
        name: 'Anthem - Blue Cross Blue Shield of Wisconsin',
        id: 'ANTHEM_BCBS_WISCONSIN',
    },
    {
        name: 'Anthem - Blue Cross Blue Shield of Wisconsin FEP',
        id: 'ANTHEM_BCBS_WISCONSIN_FEP',
    },
    { name: 'Anthem - Blue Cross of California', id: 'ANTHEM_BCBS_CALIFORNIA' },
    {
        name: 'Anthem - BlueCross BlueShield of Virginia',
        id: 'ANTHEM_BCBS_VIRGINIA',
    },
    {
        name: 'Anthem - Empire Blue Cross Blue Shield',
        id: 'ANTHEM_EMPIRE_BCBS',
    },
    { name: 'Anthem Blue Cross Blue Shield', id: 'ANTHEM_BCBS' },
    { name: 'ASONET', id: 'ASONET' },
    { name: 'Banner Health and Dental', id: 'BANNER_HEALTH' },
    { name: 'Bell Atlantic', id: 'BELL_ATLANTIC' },
    { name: 'Blue Advantage', id: 'BLUE_ADVANTAGE' },
    { name: 'Blue Care Family Plan', id: 'BLUE_CARE' },
    { name: 'Blue Cross Blue Shield of Alabama', id: 'BCBS_ALABAMA' },
    { name: 'Blue Cross Blue Shield of Arizona', id: 'BCBS_ARIZONA' },
    { name: 'Blue Cross Blue Shield of Arkansas', id: 'BCBS_ARKANSAS' },
    { name: 'Blue Cross Blue Shield of Delaware (UCCI)', id: 'BCBS_DELAWARE' },
    { name: 'Blue Cross Blue Shield of GA - Federal', id: 'BCBS_GA_FEDERAL' },
    { name: 'Blue Cross Blue Shield of Kansas', id: 'BCBS_KANSAS' },
    {
        name: 'Blue Cross Blue Shield of Kansas City (MO)',
        id: 'BCBS_KANSAS_CITY_MO',
    },
    {
        name: 'Blue Cross Blue Shield of Louisiana Advantage Plus Network',
        id: 'BCBS_LOUISIANA',
    },
    {
        name: 'Blue Cross Blue Shield of Massachusetts',
        id: 'BCBS_MASSACHUSETTS',
    },
    { name: 'Blue Cross Blue Shield of Michigan', id: 'BCBS_MICHIGAN' },
    { name: 'Blue Cross Blue Shield of Montana', id: 'BCBS_MONTANA' },
    {
        name: 'Blue Cross Blue Shield of New York - Empire',
        id: 'BCBS_NEW_YORK',
    },
    { name: 'Blue Cross Blue Shield of Oregon/ Regence', id: 'BCBS_OREGON' },
    { name: 'Blue Cross Blue Shield of Rhode Island', id: 'BCBS_RHODE_ISLAND' },
    {
        name: 'Blue Cross Blue Shield of South Carolina',
        id: 'BCBS_SOUTH_CAROLINA',
    },
    { name: 'Blue Cross Blue Shield of Tennessee', id: 'BCBS_TENNESSEE' },
    { name: 'Blue Plus Public Programs', id: 'BLUE_PLUS_PUBLIC_PROGRAMS' },
    {
        name: 'Blue Shield of California Federal (Box 272510)',
        id: 'BLUE_SHIELD_CALIFORNIA_FEDERAL',
    },
    { name: 'Blue Shield of Idaho / Regence', id: 'BLUE_SHIELD_IDAHO' },
    {
        name: 'Blue Shield of Washington / Regence of Washington Health',
        id: 'BLUE_SHIELD_WASHINGTON',
    },
    { name: 'Bridgeport Dental Service', id: 'BRIDGEPORT' },
    { name: 'Brokers National', id: 'BROKERS_NATIONAL' },
    {
        name: 'Building Service 32BJ Health Fund',
        id: 'BUILDING_SERVICE_32BJ_HEALTH_FUND',
    },
    {
        name: 'Canada Life Assurance Company',
        id: 'CANADA_LIFE_ASSURANCE_COMPANY',
    },
    {
        name: 'Chicago Transit Authority (CompBenefits)',
        id: 'CHICAGO_TRANSIT_AUTHORITY',
    },
    { name: 'Choice Plus', id: 'CHOICE_PLUS' },
    { name: 'Cigna', id: 'CIGNA' },
    { name: 'Cigna DHMO', id: 'CIGNA_DHMO' },
    { name: 'CIGNA International', id: 'CIGNA_INTERNATIONAL' },
    { name: 'Cigna Select (Formerly known as Great West)', id: 'CIGNA_SELECT' },
    { name: 'City of Chicago (CompBenefits)', id: 'CITY_CHICAGO' },
    { name: 'CompBenefits', id: 'COMP_BENEFITS' },
    {
        name: 'CompBenefits and Humana Specialty Benefits',
        id: 'COMPBENEFITS_AND_HUMANA_SPECIALTY_BENEFITS',
    },
    { name: 'Connecticut General (CIGNA)', id: 'CONNECTICUT_GENERAL_CIGNA' },
    { name: 'Continental Dental', id: 'CONTINENTAL_DENTAL' },
    {
        name: 'Correction Captains (Active and Retired)',
        id: 'CORRECTION_CAPTAINS',
    },
    {
        name: 'Council of Supervisors and Administrators',
        id: 'COUNCIL_SUPERVISORS_AND_ADMINISTRATORS',
    },
    { name: 'CustomCare (Southwestern Bell - Exec)', id: 'CUSTOMCARE' },
    { name: 'DCASI', id: 'DCASI' },
    { name: 'Decare Dental Health International (DDHI)', id: 'DECARE' },
    { name: 'Delta Dental (Northeast - ME, NH, and VT)', id: 'DD_NORTHEAST' },
    { name: 'Delta Dental TRDP (Tricare)', id: 'DD_TRICARE' },
    { name: 'Delta Dental Ins. Co. - Alabama', id: 'DD_ALABAMA' },
    { name: 'Delta Dental Ins. Co. - Florida', id: 'DD_FLORIDA' },
    { name: 'Delta Dental Ins. Co. - Georgia', id: 'DD_GEORGIA' },
    { name: 'Delta Dental Ins. Co. - Louisiana', id: 'DD_LOUISIANA' },
    { name: 'Delta Dental Ins. Co. - Mississippi', id: 'DD_MISSISSIPPI' },
    { name: 'Delta Dental Ins. Co. - Montana', id: 'DD_MONTANA' },
    { name: 'Delta Dental Ins. Co. - Nevada', id: 'DD_NEVADA' },
    { name: 'Delta Dental Ins. Co. - Texas', id: 'DD_TEXAS' },
    { name: 'Delta Dental Ins. Co. - Utah', id: 'DD_UTAH' },
    { name: 'Delta Dental of California', id: 'DD_CALIFORNIA' },
    { name: 'Delta Dental of Colorado', id: 'DD_COLORADO' },
    { name: 'Delta Dental of Connecticut', id: 'DD_CONNECTICUT' },
    { name: 'Delta Dental of Delaware', id: 'DD_DELAWARE' },
    { name: 'Delta Dental of Indiana', id: 'DD_INDIANA' },
    { name: 'Delta Dental of Iowa - Government Programs', id: 'DD_IOWA' },
    { name: 'Delta Dental of Maryland', id: 'DD_MARYLAND' },
    { name: 'Delta Dental of Michigan', id: 'DD_MICHIGAN' },
    { name: 'Delta Dental of Minnesota', id: 'DD_MINNESOTA' },
    { name: 'Delta Dental of Missouri', id: 'DD_MISSOURI' },
    { name: 'Delta Dental of Nebraska', id: 'DD_NEBRASKA' },
    { name: 'Delta Dental of New Jersey', id: 'DD_NEW_JERSEY' },
    { name: 'Delta Dental of New Mexico', id: 'DD_NEW_MEXICO' },
    { name: 'Delta Dental of New York', id: 'DD_NEW_YORK' },
    { name: 'Delta Dental of North Carolina', id: 'DD_NORTH_CAROLINA' },
    { name: 'Delta Dental of North Dakota', id: 'DD_NORTH_DAKOTA' },
    { name: 'Delta Dental of Ohio', id: 'DD_OHIO' },
    { name: 'Delta Dental of Oklahoma', id: 'DD_OKLAHOMA' },
    { name: 'Delta Dental of Pennsylvania', id: 'DD_PENNSYLVANIA' },
    { name: 'Delta Dental of Puerto Rico', id: 'DD_PUERTO_RICO' },
    { name: 'Delta Dental of Rhode Island', id: 'DD_RHODE_ISLAND' },
    {
        name: 'Delta Dental of South Carolina in Missouri',
        id: 'DELTA_DENTAL_SOUTH_CAROLINA_IN_MISSOURI',
    },
    { name: 'Delta Dental of Tennessee', id: 'DD_TENNESSEE' },
    { name: 'Delta Dental of Virginia', id: 'DD_VIRGINIA' },
    { name: 'Delta Dental of Washington', id: 'DD_WASHINGTON' },
    { name: 'Delta Dental of Washington DC', id: 'DD_WASHINGTON_DC' },
    { name: 'Delta Dental of West Virginia', id: 'DD_WEST_VIRGINIA' },
    { name: 'DeltaCare USA - Claims', id: 'DELTACARE_USA_CLAIMS' },
    { name: 'DeltaCare USA - Encounters', id: 'DELTACARE_USA_ENCOUNTERS' },
    { name: 'Dental Benefit Providers', id: 'DENTAL_BENEFIT_PROVIDERS' },
    { name: 'Dental Guard Preferred', id: 'DENTAL_GUARD_PREFERRED' },
    {
        name: 'Deseret Mutual Benefit Administrators (DMBA)',
        id: 'DESERET_MUTUAL_BENEFIT_ADMINISTRATORS',
    },
    {
        name: 'Doctors Council Benefit Fund',
        id: 'DOCTORS_COUNCIL_BENEFIT_FUND',
    },
    { name: 'EHI, EHIC', id: 'EHI,_EHIC' },
    { name: 'EMPHESYS', id: 'EMPHESYS' },
    {
        name: 'Employee Benefit Management Services, Inc. (EBMS)',
        id: 'EMPLOYEE_BENEFIT_MANAGEMENT_SERVICES',
    },
    { name: 'Employee Benefit Services', id: 'EMPLOYEE_BENEFIT_SERVICES' },
    {
        name: 'Employers Health Insurance of Wisconsin',
        id: 'EMPLOYERS_HEALTH_INSURANCE_WISCONSIN',
    },
    { name: 'Equicor / Equitable', id: 'EQUICOR_EQUITABLE' },
    {
        name: 'First Commonwealth HMO Dental Plan',
        id: 'FIRST_COMMONWEALTH_HMO_DENTAL_PLAN',
    },
    { name: 'First Reliance Standard', id: 'FIRST_RELIANCE_STANDARD' },
    { name: 'FlexCare', id: 'FLEXCARE' },
    { name: 'Florida Combined Life (Dental)', id: 'FLORIDA_COMBINED_LIFE' },
    { name: 'Florida Power &amp; Light', id: 'FLORIDA_POWER_LIGHT' },
    { name: 'GIC', id: 'GIC' },
    { name: 'Golden West Dental', id: 'GOLDEN_WEST' },
    { name: 'Guardian Life Insurance Co. of America', id: 'GUARDIAN' },
    { name: 'Hawaii Dental Service', id: 'HAWAII_DENTAL_SERVICE' },
    { name: 'HDS Medicaid', id: 'HDS_MEDICAID' },
    { name: 'Healthsource Provident', id: 'HEALTHSOURCE_PROVIDENT' },
    { name: 'Hershey Healthsmile', id: 'HERSHEY_HEALTHSMILE' },
    { name: 'Humana', id: 'HUMANA' },
    {
        name: 'Humana CompBenefits Federal Plan Dental',
        id: 'HUMANA_COMPBENEFITS_FEDERAL_PLAN_DENTAL',
    },
    {
        name: 'Humana Specialty Benefits Claim',
        id: 'HUMANA_SPECIALTY_BENEFITS_CLAIM',
    },
    {
        name: 'Humana Specialty Benefits Florida Healthy Kids Dental',
        id: 'HUMANA_SPECIALTY_BENEFITS_FLORIDA_HEALTHY_KIDS_DENTAL',
    },
    {
        name: 'Humana Specialty Benefits State of Florida Dental',
        id: 'HUMANA_SPECIALTY_BENEFITS_STATE_FLORIDA_DENTAL',
    },
    {
        name:
            'Indiana/Kentucky/Ohio Regional Council of Carpenters Welfare Fund',
        id: 'COUNCIL_CARPENTERS_WELFARE_FUND',
    },
    {
        name:
            'International Brotherhood of Electrical Workers (IBEW), Local 38 Health &amp; Welfare Fund',
        id: 'INTERNATIONAL_BROTHERHOOD_ELECTRICAL_WORKERS',
    },
    { name: 'LifeRe', id: 'LIFERE' },
    { name: 'Managed Dental Care Network', id: 'MANAGED_DENTAL_CARE_NETWORK' },
    { name: 'Marriott', id: 'MARRIOTT' },
    { name: 'Medicaid of Alabama', id: 'MEDICAID_ALABAMA' },
    { name: 'Medicaid of Arkansas', id: 'MEDICAID_ARKANSAS' },
    { name: 'Medicaid of Connecticut', id: 'MEDICAID_CONNECTICUT' },
    { name: 'Medicaid of Indiana', id: 'MEDICAID_INDIANA' },
    { name: 'Medicaid of Michigan', id: 'MEDICAID_MICHIGAN' },
    { name: 'Medicaid of Minnesota', id: 'MEDICAID_MINNESOTA' },
    { name: 'Medicaid of New York', id: 'MEDICAID_NEW_YORK' },
    { name: 'Medicaid of Utah', id: 'MEDICAID_UTAH' },
    { name: 'Medicaid of Washington', id: 'MEDICAID_WASHINGTON' },
    { name: 'MetLife', id: 'METLIFE' },
    {
        name: 'Minnesota Blue Cross Dental (UCCI)',
        id: 'MINNESOTA_BLUE_CROSS_DENTAL_(UCCI)',
    },
    { name: 'New York City Retirees', id: 'NEW_YORK_CITY_RETIREES' },
    { name: 'NWA Claims', id: 'NWA_CLAIMS' },
    {
        name: 'NYC Municipal Plumber/Pipefitters',
        id: 'NYC_MUNICIPAL_PLUMBER/PIPEFITTERS',
    },
    { name: 'ONE Health Plan Inc.', id: 'ONE_HEALTH_PLAN_INC.' },
    {
        name: 'Organization of Staff Analysts Welfare Fund',
        id: 'ORGANIZATION_STAFF_ANALYSTS_WELFARE_FUND',
    },
    { name: 'Painter Local 155 Welfare', id: 'PAINTER_LOCAL' },
    { name: 'Painting Insurance Fund DC9', id: 'PAINTING_INSURANCE_FUND_DC9' },
    { name: 'Physicians Mutual (Dental)', id: 'PHYSICIANS_MUTUAL' },
    {
        name: 'Preferred Dental Organization (PDO)',
        id: 'PREFERRED_DENTAL_ORGANIZATION',
    },
    { name: 'PrimeWest', id: 'PRIMEWEST' },
    { name: 'Provident Life &amp; Casualty Ins. Co.', id: 'PROVIDENT_LIFE' },
    {
        name: 'Provident Life and Accident Ins. Co.',
        id: 'PROVIDENT_LIFE_AND_ACCIDENT',
    },
    { name: 'Provident Preferred Network', id: 'PROVIDENT_PREFERRED_NETWORK' },
    { name: 'Prudential Administered by Aetna', id: 'PRUDENTIAL_AETNA' },
    {
        name: 'Public Employee Health Program (PEHP)',
        id: 'PUBLIC_EMPLOYEE_HEALTH_PROGRAM',
    },
    { name: 'Reliance Standard Life', id: 'RELIANCE_STANDARD_LIFE' },
    { name: 'Sanitation Officers Local 444', id: 'SANITATIONFICERS_LOCAL' },
    { name: 'Securian Dental', id: 'SECURIAN_DENTAL' },
    { name: 'Securian/Patriot Dental', id: 'SECURIAN/PATRIOT_DENTAL' },
    { name: 'Security Life Insurance', id: 'SECURITY_LIFE_INSURANCE' },
    { name: 'SelectHealth', id: 'SELECTHEALTH' },
    {
        name: 'SIDS (Self Insured Dental Services)',
        id: 'SELF_INSURED_DENTAL_SERVICES',
    },
    { name: 'Southwestern Bell', id: 'SOUTHWESTERN_BELL' },
    {
        name: 'Southwestern Bell Exec. - Custom Care',
        id: 'SOUTHWESTERN_BELL_EXEC',
    },
    { name: 'Standard Insurance', id: 'STANDARD_INSURANCE' },
    {
        name: 'Standard Insurance Co. of New York',
        id: 'STANDARD_INSURANCE_NEW_YORK',
    },
    { name: 'Sturm &amp; Associates', id: 'STURM_ASSOCIATES' },
    {
        name: 'Suffolk County Municipal Employees Benefit Fund',
        id: 'SUFFOLK_COUNTY_MUNICIPAL_EMPLOYEES_BENEFIT_FUND',
    },
    { name: 'Target Dental Services', id: 'TARGET_DENTAL_SERVICES' },
    { name: 'TDC (The Dental Companies)', id: 'TDC' },
    { name: 'Tricare Active Reservists', id: 'TRICARE_ACTIVE_RESERVISTS' },
    { name: 'TRICARE Dental Program (TDP)', id: 'TRICARE_DENTAL_PROGRAM' },
    {
        name: 'Tricare Retiree Dental Program',
        id: 'TRICARE_RETIREE_DENTAL_PROGRAM',
    },
    {
        name: 'Trigon Blue Cross/Blue Shield of Colorado',
        id: 'TRIGON_BCBS_COLORADO',
    },
    {
        name: 'Trigon Blue Cross/Blue Shield of Virginia',
        id: 'TRIGON_BCBS_VIRGINIA',
    },
    { name: 'Trigon Insurance Company', id: 'TRIGON_INSURANCE_COMPANY' },
    { name: 'TRW', id: 'TRW' },
    { name: 'TSRDP Dental Claims', id: 'TSRDP_DENTAL_CLAIMS' },
    { name: 'UCare', id: 'UCARE' },
    { name: 'UFT Welfare Fund', id: 'UFT_WELFARE_FUND' },
    { name: 'UNICARE', id: 'UNICARE' },
    { name: 'UNICARE of Texas - HMO', id: 'UNICARE_TEXAS_HMO' },
    { name: 'UNICARE Special Accounts', id: 'UNICARE_SPECIAL_ACCOUNTS' },
    {
        name: 'United Concordia (Encounters)',
        id: 'UNITED_CONCORDIA_ENCOUNTERS',
    },
    {
        name: 'United Concordia - Dental Plus - PA Blue Shield',
        id: 'UNITED_CONCORDIA_PA_BLUE_SHIELD',
    },
    {
        name: 'United Concordia - Federal Employees Program',
        id: 'UNITED_CONCORDIA_FEDERAL_EMPLOYEES_PROGRAM',
    },
    {
        name: 'United Concordia - Tricare Dental Plan',
        id: 'UNITED_CONCORDIA_TRICARE_DENTAL_PLAN',
    },
    { name: 'United Concordia', id: 'UNITED_CONCORDIA' },
    { name: 'United Healthcare', id: 'UNITED_HEALTHCARE' },
    { name: 'Varian Health Care Plan', id: 'VARIAN_HEALTH_CARE_PLAN' },
    { name: 'Wellpoint Dental Services', id: 'WELLPOINT' },
];

export default payerList;
