import {
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_GENERALDENTIST,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_ORALSURGERY,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_ORTHODONTICS,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_PERIODONTICS,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_PROSTHODONTICS,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_ENDODONTICS,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_PEDODONTICS,
} from '../strings/messageStrings';

const GENERAL_DENTIST = 'General Dentist';
const ENDODONTICS = 'Endodontics';
const ORAL_SURGERY = 'Oral Surgery';
const ORTHODONTICS = 'Orthodontics';
const PEDODONTICS = 'Pedodontics';
const PERIODONTICS = 'Periodontics';
const PROSTHODONTICS = 'Prosthodontics';

export const DENTIST_SPECIALTY_LIST = [
    GENERAL_DENTIST,
    ENDODONTICS,
    ORAL_SURGERY,
    ORTHODONTICS,
    PEDODONTICS,
    PERIODONTICS,
    PROSTHODONTICS,
];

export const DENTIST_SPECIALTY_TEXTS = {
    [GENERAL_DENTIST]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_GENERALDENTIST,
    [ENDODONTICS]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_ENDODONTICS,
    [ORAL_SURGERY]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_ORALSURGERY,
    [ORTHODONTICS]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_ORTHODONTICS,
    [PEDODONTICS]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_PEDODONTICS,
    [PERIODONTICS]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_PERIODONTICS,
    [PROSTHODONTICS]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_PROSTHODONTICS,
};
