import {
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_ALLPROCEDURES,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_FILLINGS,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_CROWNS,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_ROOTCANALS,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_GUMSURGERY,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_DEEPCLEANING,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_WHITENING,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_IMPLANTPLACEMENT,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_IMPLANTCROWN,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_EXTRACTIONS,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_DENTURES,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_BRACES,
    BOOKAPPOINTMENT_BOOKANAPPOINTMENT_EXAMS,
} from '../strings/messageStrings';

const ALL_PROCEDURES = 'All procedures';
const EXAMS = 'Exams';
const FILLINGS = 'Fillings';
const CROWNS_BRIDGES_VENEERS = 'Crowns, Bridges, Veneers';
const ROOT_CANALS = 'Root Canals';
const GUM_SURGERY_GRAFTING = 'Gum Surgery / Grafting';
const DEEP_CLEANING = 'Deep Cleaning';
const WHITENING_COSMETIC = 'Whitening / Cosmetic';
const IMPLANT_PLACEMENT = 'Implant placement';
const IMPLANT_CROWN = 'Implant crown';
const EXTRACTIONS_SURGERY = 'Extractions / Surgery';
const DENTURES = 'Dentures';
const BRACES = 'Braces';

export const PROCEDURE_LIST = [
    ALL_PROCEDURES,
    EXAMS,
    FILLINGS,
    CROWNS_BRIDGES_VENEERS,
    ROOT_CANALS,
    GUM_SURGERY_GRAFTING,
    DEEP_CLEANING,
    WHITENING_COSMETIC,
    IMPLANT_PLACEMENT,
    IMPLANT_CROWN,
    EXTRACTIONS_SURGERY,
    DENTURES,
    BRACES,
];

export const PROCEDURE_TEXTS = {
    [ALL_PROCEDURES]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_ALLPROCEDURES,
    [EXAMS]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_EXAMS,
    [FILLINGS]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_FILLINGS,
    [CROWNS_BRIDGES_VENEERS]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_CROWNS,
    [ROOT_CANALS]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_ROOTCANALS,
    [GUM_SURGERY_GRAFTING]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_GUMSURGERY,
    [DEEP_CLEANING]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_DEEPCLEANING,
    [WHITENING_COSMETIC]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_WHITENING,
    [IMPLANT_PLACEMENT]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_IMPLANTPLACEMENT,
    [IMPLANT_CROWN]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_IMPLANTCROWN,
    [EXTRACTIONS_SURGERY]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_EXTRACTIONS,
    [DENTURES]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_DENTURES,
    [BRACES]: BOOKAPPOINTMENT_BOOKANAPPOINTMENT_BRACES,
};
